package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"
	"fmt"
	postgres "videoApi/graph/connection"
	"videoApi/graph/model"
)

// CreateVideo is the resolver for the createVideo field.
func (r *mutationResolver) CreateVideo(ctx context.Context, input model.NewVideo) (*model.Video, error) {
	//panic(fmt.Errorf("not implemented: CreateVideo - createVideo"))

	conn := postgres.DB
	res := model.Video{
		Name:   input.Name,
		URL:    input.URL,
		Author: input.Author,
	}

	err := conn.Create(&res).Error

	if err != nil {
		return nil, err
	}

	fmt.Println("data inserted successfully")

	return &res, nil
}

// UpdateVideo is the resolver for the updateVideo field.
func (r *mutationResolver) UpdateVideo(ctx context.Context, input model.UpdateVideo) (*model.Video, error) {
	//panic(fmt.Errorf("not implemented: UpdateVideo - updateVideo"))
	conn := postgres.DB

	var vid model.Video

	err := conn.First(&vid, input.ID).Error
	if err != nil {
		return nil, err
	}

	if input.Name != "" {
		vid.Name = input.Name
	}

	if input.URL != "" {
		vid.URL = input.URL
	}

	if input.Author != nil {
		vid.Author = *input.Author
	}

	// Save the updated video back to the database
	if err := conn.Save(&vid).Error; err != nil {
		return nil, err
	}
	return &vid, err
}

// RemoveVideo is the resolver for the removeVideo field.
func (r *mutationResolver) RemoveVideo(ctx context.Context, input model.DeleteVideo) (string, error) {
	//panic(fmt.Errorf("not implemented: RemoveVideo - removeVideo"))
	conn := postgres.DB
	res := model.Video{
		ID: input.ID,
	}

	err := conn.Delete(&res).Error
	if err != nil {
		// Handle the error, e.g., return an error response.
		return "data not deleted", err
	}

	return "data deleted", nil
}

// Videos is the resolver for the videos field.
func (r *queryResolver) Videos(ctx context.Context) ([]*model.Video, error) {
	// panic(fmt.Errorf("not implemented: Videos - videos"))

	conn := postgres.DB

	var vdo []*model.Video

	err := conn.Find(&vdo).Error

	if err != nil {
		// Handle the error, e.g., return an error response.
		return nil, err
	}

	return vdo, nil
}

// Videoid is the resolver for the videoid field.
func (r *queryResolver) Videoid(ctx context.Context, id int) (*model.Video, error) {
	//panic(fmt.Errorf("not implemented: Videoid - videoid"))
	conn := postgres.DB
	var vdo model.Video

	err := conn.First(&vdo, id).Error
	if err != nil {
		return nil, err
	}

	return &vdo, err
}

// Videoname is the resolver for the videoname field.
func (r *queryResolver) Videoname(ctx context.Context, name *string) ([]*model.Video, error) {
	//panic(fmt.Errorf("not implemented: Videoname - videoname"))

	conn := postgres.DB
	var vdo []*model.Video
	res := &model.Video{
		Name: *name,
	}
	err := conn.Find(&vdo, res).Error

	if err != nil {
		return nil, err
	}

	return vdo, err
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
