// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DeleteVideo struct {
	ID int `json:"id"`
}

type NewVideo struct {
	ID     int    `json:"id"`
	Name   string `json:"name"`
	URL    string `json:"url"`
	Author string `json:"author"`
}

type UpdateVideo struct {
	ID     int     `json:"id"`
	Name   string  `json:"name"`
	URL    string  `json:"url"`
	Author *string `json:"author,omitempty"`
}

type Video struct {
	ID     int    `json:"id"`
	Name   string `json:"name"`
	URL    string `json:"url"`
	Author string `json:"author"`
}
